POST http://localhost:3001/api/categories
Content-Type: application/json

{
    "name" : "big",
    "questions" : [
        {
            "title": "is this still still correct (new)?",
            "options": [
                {
                    "text": "yes",
                    "isCorrect": true
                },
                {
                    "text": "no",
                    "isCorrect": false
                },
                {
                    "text": "no",
                    "isCorrect": false
                },
                {
                    "text": "no",
                    "isCorrect": false
                }
            ]
        }
    ]
}